### ISSUE TITLE
Error loading script

### ISSUE THREAD

**Issue by kkostov** [TelemetryDeck/JavaScriptSDK#19]
Hi 👋 ,

While following the guide at https://telemetrydeck.com/docs/guides/javascript-setup/ I added the TD script to the head section as instructed, however the script throws an error when loading:

In Safari 16.5:
<img width="959" alt="Screenshot 2023-06-01 at 11 55 17" src="https://github.com/TelemetryDeck/JavaScriptSDK/assets/4718042/16bc7936-5b29-4af8-a729-5778dbb1d46b">

In Firefox 113.0.2:
<img width="1223" alt="Screenshot 2023-06-01 at 11 59 16" src="https://github.com/TelemetryDeck/JavaScriptSDK/assets/4718042/be544643-7648-4758-839e-a48b145b7fcb">

```html
...
 <script src="https://unpkg.com/@telemetrydeck/sdk/dist/telemetrydeck.min.js" defer></script>
```

The error occurs before calling any of the setup functions (like adding app key and user identifier).

Could you help me spot what I'm doing wrong?

**Comment by winsmith** [comment]
Hi Konstantin, I'm so sorry for overlooking this issue. Can you please check wether updating the "defer" parameter like so helps with the problem?

```
<script src="https://unpkg.com/@telemetrydeck/sdk/dist/telemetrydeck.min.js" defer="defer"></script>
```

If yes, this is an error in our docs that I'll need to fix.

**Comment by kkostov** [comment]
No worries, I will give it a try and let you know. In the meantime, I opted for using the rest api directly from the server, following https://telemetrydeck.com/docs/api/ingestion-api-spec/#ingest-endpoint

**Comment by winsmith** [comment]
We're changing the way we provide analytics for websites soon so I'm closing this ticket because it doesnt apply anymore.
