### ISSUE TITLE
USER_IDENTIFIER should be optional

### ISSUE THREAD

**Issue by Timac** [TelemetryDeck/JavaScriptSDK#21]
I used the JavascriptSDK on a website where I don't have a user identifier (and don't want to have one). When reading the documentation at https://telemetrydeck.com/docs/guides/javascript-setup/ , I saw the section `Optional: User Identifiers` and the sentence `If you have none, consider anonymous`.

I assumed that I could avoid to give a `user` and simply use something like:

```
td.push(["app", YOUR_APP_ID], ["signal"]);
```

This resulted in an error:

<img width="295" alt="Error" src="https://github.com/TelemetryDeck/JavaScriptSDK/assets/738543/e3c7e0a8-039b-40c3-ad6c-0a0c1491c2a2">

See corresponding documentation:

<img width="766" alt="Documentation" src="https://github.com/TelemetryDeck/JavaScriptSDK/assets/738543/5c09a030-9f3f-4bc7-8571-5faeb1e303ba">

I would expect not to have an error if you pass no user. The backend should automatically assign a signal with no user to an anonymous user.

**Comment by winsmith** [comment]
This is fixed with the upcoming JS SDK v 2 https://github.com/TelemetryDeck/JavaScriptSDK/tree/pichfl/new-sdk
