### ISSUE TITLE
javascript sdk not working at all

### ISSUE THREAD

**Issue by didamaran** [TelemetryDeck/JavaScriptSDK#5]
tried both ways exactly as described in the docs: importing the sdk via a script tag in the header of a site and importing the npm package and then building the site.

**header script tag:** no errors come up and the network tab shows:
```
Request URL: https://unpkg.com/@telemetrydeck/sdk/dist/telemetrydeck.min.js
Request Method: GET
Status Code: 302 
Remote Address: [2606:4700::6810:7aaf]:443
Referrer Policy: strict-origin-when-cross-origin
```
no payload is sent

**npm import:** 
```
import { TelemetryDeck } from 'telemetry-deck';
```
throws an error "dependency not found"

System: node 14.17.0, npm 7.24.0, vue with nuxt 2.15.7

**Comment by winsmith** [comment]
Thanks for reporting, that sounds serious! I'll have a look and try to reproduce this

**Comment by winsmith** [comment]
I think there is an error in the readme file. Can you try if this tutorial works for you?

https://telemetrydeck.com/pages/javascript-setup.html

**Comment by didamaran** [comment]
I'm afraid to say that I used the exact code from the tut

**Comment by winsmith** [comment]
Hi, sooo after looking into the problem, @pichfl and I found two issues:

## 1) The README had an incorrect `import` statement

The correct import should read `import { TelemetryDeck } from '@telemetrydeck/sdk';`.

This is the cause for the npm import code not working in your post. 

## 2) The release process that pushes new versions to NPM had a problem which is now circumvented.

I couldn't reproduce your first issue with the script tags, but the problem might have stemmed from there. Here's a [codepen](https://codepen.io/winsmith/pen/popEyMY) that shows that it works now. 

I hope that helps! Thank you very much for opening this ticket, we hope TelemetryDeck will bring you lots of joy and value :D~

**Comment by didamaran** [comment]
wow, that was fast! i will look into it tomorrow

**Comment by didamaran** [comment]
couldnt wait and tried the webpack variant, but without luck.
the import seems to work now, but it results in an error:

Module parse failed: Unexpected token (35:26)                                                                                                                    friendly-errors 22:31:08
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const { target, app, user } = options;
| 
>     this.target = target ?? 'https://nom.telemetrydeck.com/v1/';
|     this._app = app;
|     this._user = user;
                                                                                                                                                                 friendly-errors 22:31:08
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/blog.vue?vue&type=script&lang=js& 32:0-51 69:14-27
 @ ./layouts/blog.vue?vue&type=script&lang=js&
 @ ./layouts/blog.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js

**Comment by didamaran** [comment]
tried it just now with the script tag in the header, but there are no signals reaching the telemetrydeck dashboard. you can take at look at the site here: https://contentplanr.com/de/

**Comment by winsmith** [comment]
You have a typo here: 

```js
 window.td = window.td || [],
``` 

this line has a , after it but it should be a semicolon

**Comment by didamaran** [comment]
oh man, my bad, i'm sorry!

**Comment by pichfl** [comment]
As of this moment you moved the configuration of the SDK to a separate JS file which also loads deferred. This is not what the README describes (having an inline script tag for the config and deferred loading of the SDK) and therefore is untested behavior. 

That being said, I still think it should be a valid use case for the SDK and we'll make some adjustments to make this work. 

Regarding importing the module from npm directly: Can you provide a reproduction of this in a basic nuxt project? I haven't used Nuxt.js yet, but testing with a pure Webpack seems to work just fine.
