### ISSUE TITLE
Error when running in non-secure mode

### ISSUE THREAD

**Issue by plaetzchen** [TelemetryDeck/JavaScriptSDK#9]
I am trying to integrate TelementryDeck into a simple static website ([statushook.cool](https://www.statushook.cool)) and I get an error in the console of my developer tools and TelemetryDeck does not log any signals.

In Chrome the message is:
`TypeError: Cannot read properties of undefined (reading 'digest')`

In Safari 15.5 the message is:
`TypeError: undefined is not an object (evaluating 'crypto.subtle.digest')`

Is there a way t fix this? Feel free to poke into the website code to see how it's set up in the `<head>`

**Comment by winsmith** [comment]
Hi, I can reproduce this on Edge 101.0.1210.53. It seems to work on Safari 15.4. I'll investigate, thanks for reporting.

<img width="486" alt="Screenshot 2022-05-24 at 15 46 56" src="https://user-images.githubusercontent.com/954120/170051083-356140a5-6f4a-4961-a0c0-4d4d3a828eea.png">

<img width="626" alt="Screenshot 2022-05-24 at 15 45 25" src="https://user-images.githubusercontent.com/954120/170050707-a95dad50-a2fc-40f7-bc9e-2e49764d974d.png">

**Comment by winsmith** [comment]
Hi, here's an update: we're using the SubtleCrypto.digest function to calculate SHA256 hashes for user identifiers. [According to MDN, this function is not available in non-https-contexts.](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest)

I just opened your website again to check if it was HTTP or HTTPS and it is HTTPS but I also can't reproduce the error anymore. Did you change something ?

**Comment by plaetzchen** [comment]
I did not change anything but you are right, it works when I use HTTPS. Once you have manually switched to HTTPS it is also enforced by your browser but the forward from HTTP to HTTPS is missing, I will try to fix that. Thank you

**Comment by plaetzchen** [comment]
Confirmed, after enforcing HTTPS for every one it works as expected. My worth adding a note to the docs

**Comment by winsmith** [comment]
I'll leave this issue open so we can have a look at improving this!
